name: Build dependencies

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: vcpkg.json

env: 
    # https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache
    VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [x64-linux, x64-windows]
        include:
          - target: x64-linux
            os: ubuntu-latest
            vcpkg: vcpkg
            vcpkg_bootstrap: ./bootstrap-vcpkg.sh
          - target: x64-windows
            os: windows-latest
            vcpkg: vcpkg.exe
            vcpkg_bootstrap: bootstrap-vcpkg.bat
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout vcpkg
        uses: actions/checkout@v4
        with:
          path: vcpkg
          fetch-depth: 0
          repository: microsoft/vcpkg
      - name: Checkout vcpkg.json
        uses: actions/checkout@v4
        with:
          path: config
          sparse-checkout: vcpkg.json
      - name: Install vcpkg.json
        run: mv config/vcpkg.json vcpkg/
      - name: Configure caching
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Bootstrap vcpkg
        run: ${{ matrix.vcpkg_bootstrap }}
        working-directory: vcpkg
      - name: Build libraries
        run: ${{ matrix.vcpkg }} install --triplet ${{ matrix.target }}
        working-directory: vcpkg
      - run: ls vcpkg/vcpkg_installed/${{matrix.target}}/bin
      - uses: actions/upload-artifact@v4
        with:
          name: dependencies-${{ matrix.target }}
          if-no-files-found: error
          path: |
            vcpkg/vcpkg_installed/${{ matrix.target }}/bin/graphqlservice*
            vcpkg/vcpkg_installed/${{ matrix.target }}/bin/graphqlpeg*
            vcpkg/vcpkg_installed/${{ matrix.target }}/bin/graphqljson*
            vcpkg/vcpkg_installed/${{ matrix.target }}/bin/graphqlresponse*
            vcpkg/vcpkg_installed/${{ matrix.target }}/bin/zlib*
            vcpkg/vcpkg_installed/${{ matrix.target }}/bin/uv*
