name: Build dependencies

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: vcpkg.json

env: 
    # https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache
    VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # target: [x64-linux, x64-windows]
        target: [x64-windows]
        include:
          # - target: x64-linux
          #   os: ubuntu-latest
          #   vcpkg: vcpkg
          #   vcpkg_bin: installed/x64-linux/bin
          - target: x64-windows
            os: windows-latest
            vcpkg: vcpkg.exe
            vcpkg_bin: vcpkg\installed\x64-windows\bin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout vcpkg
        uses: actions/checkout@v4
        with:
          path: vcpkg
          fetch-depth: 0
          repository: microsoft/vcpkg
      - name: Checkout vcpkg.json
        uses: actions/checkout@v4
        with:
          path: config
          sparse-checkout: vcpkg.json
      - name: Install vcpkg.json
        run: mv config/vcpkg.json vcpkg/
      - name: Configure caching
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Bootstrap vcpkg
        run: bootstrap-vcpkg
        working-directory: vcpkg
      - run: ls vcpkg
      - run: ls vcpkg/vcpkg_installed/${{matrrix.target}}/bin
      - name: Build libraries
        run: ${{ matrix.vcpkg }} install --binarysource ../binarysource --triplet ${{ matrix.target }}
        working-directory: vcpkg
      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: |
            vcpkg/vcpkg_installed/${{ matrix.target }}/graphqlservice*
            vcpkg/vcpkg_installed/${{ matrix.target }}/graphqlpeg*
            vcpkg/vcpkg_installed/${{ matrix.target }}/graphqljson*
            vcpkg/vcpkg_installed/${{ matrix.target }}/graphqlresponse*
            vcpkg/vcpkg_installed/${{ matrix.target }}/zlib*
            vcpkg/vcpkg_installed/${{ matrix.target }}/uv*
