name: Build dependencies

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: vcpkg.json

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # target: [x64-linux, x64-windows]
        os: [x64-windows]
        include:
          # - target: x64-linux
          #   bootstrap: bootstrap-vcpkg.sh
          #   cache_dir: "$HOME/.cache/vcpkg/archives"
          #   os: ubuntu-latest
          #   vcpkg: vcpkg
          #   vcpkg_bin: installed/x64-linux/bin
          - target: x64-windows
            bootstrap: bootstrap-vcpkg
            cache_dir: "%LOCALAPPDATA%\vcpkg\archives"
            os: windows-latest
            vcpkg: .\vcpkg.exe
            vcpkg_bin: installed\x64-windows\bin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout vcpkg
        uses: actions/checkout@v4
        with:
          path: vcpkg
          repository: microsoft/vcpkg
      - name: Checkout vpckg.json
        uses: actions/checkout@v4
        with:
          sparse-checkout: vcpkg.json
      - name: Maintain binary cache
        uses: actions/cache@v4
        with:
          path: ${{ matrix.cache_dir }}
          key: ${{ runner.os }}-vcpkg
      - name: Bootstrap vcpkg
        run: ${{ matrix.bootstrap }}
        working-directory: vpckg
      - name: Build libraries
        run: ${{ matrix.vcpkg }} install
        working-directory: vcpkg
      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: |
            ${{ matrix.vcpkg_bin }}/graphqlservice*
            ${{ matrix.vcpkg_bin }}/graphqlpeg*
            ${{ matrix.vcpkg_bin }}/graphqljson*
            ${{ matrix.vcpkg_bin }}/graphqlresponse*
            ${{ matrix.vcpkg_bin }}/zlib*
            ${{ matrix.vcpkg_bin }}/uv*
