name: Build dependencies

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: vcpkg.json

env: 
    # https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache
    VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [Linux-x86_64, Win64]
        include:
          - target: Linux-x86_64
            triplet: x64-linux
            os: ubuntu-latest
            vcpkg: vcpkg
            vcpkg_bootstrap: ./bootstrap-vcpkg.sh
            artifacts: |
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/lib/libgraphqlservice.a
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/lib/libgraphqlpeg.a
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/lib/libgraphqljson.a
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/lib/libgraphqlresponse.a
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/lib/libuSockets.a
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/lib/libz.a
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/lib/libuv.a
          - target: Win64
            triplet: x64-windows
            os: windows-latest
            vcpkg: vcpkg.exe
            vcpkg_bootstrap: bootstrap-vcpkg.bat
            artifacts: |
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/bin/graphqlservice.dll
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/bin/graphqlpeg.dll
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/bin/graphqljson.dll
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/bin/graphqlresponse.dll
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/bin/zlib1.dll
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/bin/uv.dll
            artifacts_debug: |
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/bin/graphqlservice.*
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/bin/graphqlpeg.*
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/bin/graphqljson.*
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/bin/graphqlresponse.*
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/bin/zlib.*
              vcpkg/vcpkg_installed/${{ matrix.triplet }}/bin/uv.*
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout vcpkg
        uses: actions/checkout@v4
        with:
          path: vcpkg
          fetch-depth: 0
          repository: microsoft/vcpkg
      - name: Checkout vcpkg.json
        uses: actions/checkout@v4
        with:
          path: config
          sparse-checkout: vcpkg.json
      - name: Install vcpkg.json
        run: mv config/vcpkg.json vcpkg/
      - name: Configure caching
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Bootstrap vcpkg
        run: ${{ matrix.vcpkg_bootstrap }}
        working-directory: vcpkg
      - name: Build libraries (dynamic)
        run: ${{ matrix.vcpkg }} install --triplet ${{ matrix.triplet }}
        working-directory: vcpkg
      - name: Build libraries (static)
        run: ${{ matrix.vcpkg }} install --triplet ${{ matrix.triplet }}-static
        working-directory: vcpkg
      - run: ls vcpkg/vcpkg_installed/${{ matrix.triplet }}/tools
      - name: Upload libraries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: ${{ matrix.artifacts }}
          if-no-files-found: error
      - name: Upload debug libraries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-debug
          path: ${{ matrix.artifacts_debug }}
          if-no-files-found: error
